import type { Metadata } from "next";
import Link from "next/link";
import "../t2a-case-study/t2a-case-study.css";
import "./point-line-scene-framework.css";
import "./evidence-integrity.css";
import { evaluationSystemEvidence, publicEvidenceStatusLabels } from "../../src/data/evaluation-system-evidence";

export const metadata: Metadata = {
  title: "PLS-Eval｜Point–Line–Scene 结构化诊断评测",
  description: "PLS-Eval 将生成任务拆成 Point、Line、Scene 三层可验证约束，并以独立 Quality 轴、显式参考链与单元级记录定位可观察失败。",
  keywords: ["PLS-Eval", "Point-Line-Scene", "Failure Localization", "Reference-aware Diagnosis", "生成式音频评测"],
  alternates: { canonical: "/point-line-scene-framework" },
};

const layers = [["POINT", "点：局部事实", "Local / Atomic", "事件、声源、属性、材质、计数"], ["LINE", "线：事实关系", "Relational", "时间、空间、因果、交互、动态 / 声画同步"], ["SCENE", "面：整体场景", "Graph-level", "环境、层级、语境、显著性、整体一致性"]] as const;
const regressionCases = [["Exact-count", "Repeated Diagnostic Pattern", "3→4→4 在 3 个可精确判定案例中重复出现。"], ["Onset", "Not Replicated", "Round-2 未复现 audio_early。"], ["Dynamic", "Mixed / Refined", "有边界响应，但连续 source-motion 跟随不足。"], ["Cross-shot", "Not Replicated", "未支持一般化的 Cut→Audio Loss 解释。"]] as const;
const judgeAudit = [["Detection", "Failure Recall · Balanced Accuracy"], ["Localization", "Exact Set Match · Failure Jaccard"], ["Decoupling", "Prediction Correlation · Pseudo-Decoupling"], ["Reliability", "Human Agreement · Domain Stability"]] as const;
const frontierPapers = [["OmniJudge", "结构设计与 Judge 审计", "保留分离维度，并审计失败发现能力。", "未来研究输入", "https://arxiv.org/abs/2608.24160"], ["Voice-Agent Judge", "评测器部署", "按单元验证自动评测的可靠性。", "未来研究输入", "https://arxiv.org/abs/2608.24314"], ["RubricRM", "偏好与奖励", "在固定 taxonomy 上研究任务相关偏好。", "未来研究输入", "https://arxiv.org/abs/2608.26956"]] as const;
const references = [["AudioScape-TTA", "https://arxiv.org/abs/2608.04479"], ["AnyAudio-Judge", "https://arxiv.org/abs/2606.03116"], ["Fine-Grained Feedback for TTA", "https://arxiv.org/abs/2607.13408"], ["MMAG", "https://arxiv.org/abs/2608.06900"], ["AcoustiTrace", "https://arxiv.org/abs/2608.02035"], ["AVGen-Bench", "https://arxiv.org/abs/2604.08540"], ["Production-Oriented SFX Evaluation", "https://arxiv.org/abs/2607.09973"], ["AudioRubrics", "https://arxiv.org/abs/2608.02831"], ["LALM Judge Audit", "https://arxiv.org/abs/2607.13477"], ["OmniJudge or OmniBias? D³-Omni", "https://arxiv.org/abs/2608.24160"], ["Benchmarking LLM Judges for Voice-Agent Evaluation", "https://arxiv.org/abs/2608.24314"], ["RubricRM", "https://arxiv.org/abs/2608.26956"]] as const;
function Arrow({ down = false }: { down?: boolean }) { return <span className={`pls-v21-arrow ${down ? "is-down" : ""}`} aria-hidden="true" />; }
function Heading({ index, title, children }: { index: string; title: string; children?: React.ReactNode }) { return <header className="pls-v21-heading"><p>{index}</p><h2>{title}</h2>{children && <div>{children}</div>}</header>; }

export default function PointLineSceneFrameworkPage() { return <main className="t2a-page pls-page pls-eval-page pls-v21-page">
  <header className="t2a-topbar"><Link className="wordmark" href="/" aria-label="返回作品集首页"><span className="wordmark-mark" aria-hidden="true" /><span>DU MING / AUDIO</span></Link><nav aria-label="PLS-Eval 页面导航"><Link className="topbar-mobile-only" href="/">首页</Link><a className="topbar-mobile-only" href="#reference">案例</a><a className="topbar-desktop-only" href="#framework">框架</a><a className="topbar-desktop-only" href="#reference">参考链</a><a className="topbar-desktop-only" href="#regression">回归</a><a className="topbar-desktop-only" href="#evidence-roles">证据</a><a className="topbar-desktop-only" href="#boundary">边界</a><a className="topbar-desktop-only" href="#research-details">文献</a></nav></header>

  <section className="pls-v21-hero t2a-shell"><div className="pls-v21-hero-copy"><p className="eyebrow">PLS-Eval / 结构化评测</p><p className="pls-v21-kicker">Point–Line–Scene Structured Diagnostic Evaluation</p><h1>先定位失败原因，<br />再讨论整体分数</h1><p>PLS 不从“整体分数”开始，而从“哪一项要求在哪里失败”开始。Quality（质量）独立记录，不进入 P→L→S 的层级链。</p><div className="pls-v21-hero-actions"><a className="btn btn-primary" href="#reference">查看真实案例</a><Link className="paper-link" href="/point-line-scene-framework/report/">完整报告</Link></div></div><figure className="pls-v21-core-graph" role="img" aria-label="任务要求分解为点、线、面，得到单元级记录和失败定位；质量作为独立轴从侧面进入。"><div className="pls-v21-core-node is-root">任务要求<small>Requirement</small></div><Arrow down /><div className="pls-v21-core-branches"><div className="pls-v21-core-node">点<small>POINT · 局部事实</small></div><div className="pls-v21-core-node">线<small>LINE · 关系</small></div><div className="pls-v21-core-node">面<small>SCENE · 整体场景</small></div></div><Arrow down /><div className="pls-v21-core-node is-state">单元级记录<small>Unit-level Record</small></div><Arrow down /><div className="pls-v21-core-node is-output">失败定位<small>Failure Localization</small></div><div className="pls-v21-quality-rail"><span>独立质量</span><small>Quality · 独立记录</small></div><figcaption>PLS = 结构化任务要求，再定位可观察失败项。</figcaption></figure></section>

  <section className="t2a-section t2a-shell" id="framework"><Heading index="01 / PLS + QUALITY" title="三个约束层，外加一条独立质量轴"><p>Point、Line、Scene 分别检查事实、关系和场景；Quality 只描述输出自身质量。</p></Heading><div className="pls-v21-layer-map" role="img" aria-label="Point、Line、Scene 三层约束与独立 Quality 质量轴">{layers.map(([id, title, type, items]) => <article key={id}><span>{id}</span><small>{type}</small><h3>{title}</h3><p>{items}</p></article>)}<aside><span>QUALITY</span><h3>独立质量轴</h3><p>Artifact · Noise · Clipping · Loudness · Spectral / Spatial Quality</p><strong>PLS + Q</strong></aside></div></section>

  <section className="t2a-section t2a-section-tint" id="schema"><div className="t2a-shell"><Heading index="02 / STABLE TAXONOMY × DYNAMIC SCHEMA" title="固定坐标系，按任务激活评价单元"><p>已冻结的 P1–P4、L1–L4、S1–S4 不随 Prompt 改写；每条任务只激活适用单元。</p></Heading><div className="pls-v21-schema-diagram" role="img" aria-label="稳定 taxonomy 在 prompt 激活后形成 active schema"><article><span>STABLE TAXONOMY</span><div className="pls-v21-taxonomy-dots">{["P","P","P","P","L","L","L","L","S","S","S","S"].map((item, index) => <b key={`${item}-${index}`}>{item}</b>)}</div><small>12 项冻结 Capability</small></article><Arrow /><article><span>ACTIVE SCHEMA</span><p>“金属杯被敲三次，随后滑过木桌。”</p><div className="pls-v21-active-units"><b>P1 ●</b><b>P3 ●</b><b className="is-primary">P4 ● PRIMARY</b><b>L2 ●</b><b className="is-na">S1 ○ N/A</b></div></article></div><p className="pls-v21-principle">Ontology stays stable; applicable evaluation units change with the task.</p></div></section>

  <section className="t2a-section t2a-shell" id="atomic-units"><Heading index="03 / ATOMIC EVALUATION UNIT" title="一个单元，只验证一个问题"><p>原子化让每个要求都可单独检查；它不代表预设一组示例分数。</p></Heading><div className="pls-v21-atomic-compare"><article className="is-coupled"><span>COUPLED RUBRIC</span><h3>Event + Material + Count + Order</h3><strong>ONE RESULT · FAIL ×</strong><p>失败发生在哪一项要求，不清楚。</p></article><Arrow /><article className="is-decoupled"><span>DECOUPLED UNITS</span><div><b>Event</b><b>Material</b><b>Count</b><b>Temporal Order</b></div><p>每项要求保留为可检查的 Unit-level record。</p></article></div></section>

  <section className="pls-v21-reference-band" id="reference"><div className="t2a-shell"><Heading index="04 / REFERENCE-AWARE DIAGNOSIS · CASE-SUPPORTED" title="3→4→4：比较哪一段参考链，决定问题归因"><p>P06、P10 与 R2-H1-B 在两轮中形成可精确判定的 Repeated Diagnostic Pattern。</p></Heading><div className="pls-v21-reference-chain" role="img" aria-label="Prompt count 3 到 Visual count 4 是 instruction fidelity fail，Visual count 4 到 Audio count 4 是 event correspondence pass。"><article><span>PROMPT</span><strong>3</strong><small>COUNT = 3</small></article><div className="pls-v21-reference-edge is-fail"><Arrow /><b>Instruction Fidelity<br />FAIL ×</b></div><article className="is-fail"><span>VISUAL</span><strong>4</strong><small>COUNT = 4</small></article><div className="pls-v21-reference-edge is-pass"><Arrow /><b>Event Correspondence<br />PASS ✓</b></div><article className="is-pass"><span>AUDIO</span><strong>4</strong><small>COUNT = 4</small></article></div><div className="pls-v21-attribution-compare"><div><span>WITHOUT REFERENCE CHAIN</span><strong>Audio Counting Failure <b>×</b></strong></div><div><span>WITH REFERENCE CHAIN</span><strong>Visual Instruction Failure <b>✓</b></strong></div></div><div className="pls-v21-case-links"><Link className="btn btn-primary" href="/audio-visual-evaluation">查看两轮音视频评测</Link><span>Evidence status · Repeated Diagnostic Pattern</span></div></div></section>

  <section className="t2a-section t2a-shell" id="unit-record"><Heading index="05 / UNIT-LEVEL RECORD · IMPLEMENTED" title="原始单元状态在前，聚合展示在后"><p>P06 记录保留 Capability、参考关系、Bad Case 与独立质量；Point / Line 均值只是派生视图。</p></Heading><div className="pls-v21-record-flow"><article><span>RAW STATE · P06</span><div><b>P4 Event Counting <i>5 / 5</i></b><b>L1 Onset Alignment <i>3 / 5</i></b><b>Instruction Fidelity <i className="is-fail">FAIL ×</i></b><b>Cross-modal Correspondence <i className="is-pass">PASS ✓</i></b><b>OVL <i>4 / 5</i></b></div><small><code>audio_early</code> remains observable.</small></article><Arrow /><article className="is-derived"><span>DERIVED VIEW</span><div><b>Point <i>5.00</i></b><b>Line <i>4.00</i></b><b>OVL <i>4 / 5</i></b></div><small>聚合不能反向覆盖 Facts 或 Bad Case。</small></article></div><div className="pls-v21-quality-proof"><span>H2 · RELATION CORRECTNESS</span><strong>Point 5.00 / Line 5.00</strong><b>≠</b><span>PERCEPTUAL QUALITY</span><strong>OVL 3 · <code>loudness_imbalance</code></strong><p>关系正确，输出质量仍可较低。</p></div></section>

  <section className="t2a-section t2a-section-tint" id="regression"><div className="t2a-shell"><Heading index="06 / CONTROLLED REGRESSION · IMPLEMENTED" title="发现失败后，用新样本检查是否重现"><p>Round-1 负责发现；Round-2 在生成前冻结假设、观察字段和判定规则，再更新后续排查优先级。</p></Heading><div className="pls-v21-regression-diff"><div><b>ROUND-1</b><Arrow down /><strong>Controlled Regression</strong><Arrow down /><b>ROUND-2</b></div><section>{regressionCases.map(([probe, status, detail]) => <article key={probe}><span>{probe}</span><strong>{status}</strong><small>{detail}</small></article>)}</section></div><div className="pls-v21-real-drilldown" role="img" aria-label="从 3→4→4 重复观察到精确计数回归优先级的真实证据链。"><div>{["REPEATED OBSERVATION · 3→4→4", "CAPABILITY / REFERENCE · Exact-count / P4", "CASES · P06 · P10 · R2-H1-B", "OBSERVABLE FACTS · Prompt 3 · Visual 4 · Audio 4", "ATTRIBUTION · Prompt→Visual mismatch; Visual→Audio count consistent", "ACTION · Increase exact-count regression priority"].map((item, index) => <span key={item}>{index > 0 && <Arrow down />}<b>{item}</b></span>)}</div></div></div></section>

  <section className="t2a-section t2a-shell" id="evidence-roles"><Heading index="07 / 证据分工" title="评测证据如何分工"><p>人工判断、信号诊断与结构化执行承担不同职责；它们不是一个自动路由系统。</p></Heading><div className="pls-v21-evidence-architecture" role="img" aria-label="人工评测进入评测记录和执行层；信号诊断作为独立辅助证据，模型 Judge 属于后续扩展。"><div className="pls-v21-human-lane"><span>主判断</span><article><b>人工评测</b><em>Human Evaluation</em><small>已实现</small><p>画面事实 · PLS 能力评分 · OVL · 失败案例（Bad Case）</p></article><Arrow down /><article><b>评测记录</b><em>Evaluation Record</em><small>已实现</small><p>事实 · 评分 · 参考关系 · 标签</p></article><Arrow down /><article><b>执行层 v0.1</b><em>Execution Layer</em><small>已实现</small><p>结构校验 · 维度概况 · 诊断摘要</p></article></div><aside><span>辅助证据</span><article className="is-signal"><b>信号诊断</b><em>Signal Diagnostics</em><small>已实现</small><p>文件 / 技术 · 频谱 · 空间 · 动态</p></article><p className="pls-v21-concept-link">人工对照<br />概念整合</p><article className="is-future"><b>模型评测器</b><em>Model Judge</em><small>后续扩展</small><p>尚未实现 · 需要可靠性验证</p></article></aside></div><p className="pls-v21-evidence-note">Signal Diagnostics 不自动生成或修改 PLS / OVL 评分；当前由人工分析进行对照。</p></section>

  <section className="t2a-section t2a-section-tint" id="boundary"><div className="t2a-shell"><Heading index="08 / EVIDENCE BOUNDARY" title="用四级状态区分证据与方向"><p>主体展示真实执行或案例支持的结果；尚未回填到冻结数据的设计单独标记。</p></Heading><div className="pls-v21-boundary-grid pls-v21-boundary-grid-four"><article><span>IMPLEMENTED</span><p>PLS Taxonomy / Schema v1.0 · Human Evaluation · Signal Diagnostics batch analysis · Execution Layer · Unit-level record · Controlled Regression</p></article><article><span>CASE-SUPPORTED</span><p>3→4→4 Reference-aware Diagnosis · Exact-count repeated pattern · Onset / Dynamic / Cross-shot states · Quality independence</p></article><article><span>INTEGRATED CONCEPT</span><p>Signal evidence → PLS record connection · Dependency-aware Eligibility · BLOCKED semantics · Primary Target design<br /><small>not fully executed / not backfilled</small></p></article><article><span>FUTURE EXTENSION</span><p>Audio / Omni Judge · Multi-evaluator Calibration · Preference · Dynamic Importance · Reward Model</p></article></div><p className="pls-v21-limitation"><strong>当前证据：</strong>Round-1 10 个、Round-2 6 个单次生成；不构成 multi-seed statistical experiment，也不做总体性能泛化。</p></div></section>

  <section className="t2a-section t2a-shell" id="method-extensions"><Heading index="09 / METHOD EXTENSIONS" title="尚未应用到冻结数据的方法设计"><p>下列内容不作为当前项目结果，也未回填至原始数据集。</p></Heading><details className="pls-landing-details"><summary>展开 Method Extensions / 尚未应用到冻结数据</summary><div className="pls-v21-extension-grid"><article><span>DEPENDENCY-AWARE ELIGIBILITY</span><h3>依赖感知的评价资格</h3><p>IF event exists → evaluate attribute；IF event missing → downstream attribute / relation would be BLOCKED。</p><small>PROPOSED STATE LOGIC · NOT YET APPLIED</small></article><article><span>PRIMARY TARGET + DIAGNOSTIC UNITS</span><h3>未来案例设计</h3><p>后续 focused diagnostic cases 可指定一个 Primary Target，同时保留其他适用要求作为 Diagnostic Units。</p><small>FUTURE DATASET DESIGN · NOT BACKFILLED</small></article><article><span>FUTURE METRIC DESIGN</span><h3>资格与成功率公式</h3><p>Eligibility Rate = eligible / designed<br />Conditional Accuracy = correct / eligible<br />End-to-End Success = correct / designed</p><small>FORMULA ONLY · NO PROJECT RESULT</small></article></div></details></section>

  <section className="t2a-section t2a-section-tint" id="research-details"><div className="t2a-shell"><Heading index="10 / RESEARCH FRONTIER · FUTURE" title="研究来源与未来评测"><p>文献启发后续 Judge、Preference 与 Reward 研究，不构成当前项目已部署能力。</p></Heading><div className="pls-v21-frontier">{frontierPapers.map(([title, theme, influence, label, href]) => <article key={title}><span>{theme}</span><h3>{title}</h3><p>{influence}</p><b>{label}</b><a href={href} target="_blank" rel="noreferrer">阅读论文 ↗</a></article>)}</div><details className="pls-landing-details"><summary>展开 Judge Audit / Literature-inspired · not measured in this project</summary><div className="pls-v21-audit-matrix">{judgeAudit.map(([title, metric]) => <article key={title}><h3>{title}</h3><p>{metric}</p><span>FUTURE / NOT IMPLEMENTED</span></article>)}</div><div className="pls-v21-judge-concept"><strong>AGGREGATE ACCURACY</strong><b>≠</b><strong>EXACT FAILURE LOCALIZATION</strong></div></details><details className="pls-landing-details"><summary>展开已执行的 Signal Diagnostics 指标</summary><div className="pls-v21-signal-details"><div>{evaluationSystemEvidence.systemStatuses.map((item) => <article key={item.label}><span>{publicEvidenceStatusLabels[item.status]}</span><strong>{item.label}</strong></article>)}</div><p>{evaluationSystemEvidence.publicBoundary}</p></div></details><details className="pls-landing-details"><summary>展开 12 条参考文献</summary><ol className="pls-reference-list">{references.map(([title, href]) => <li key={href}><a href={href} target="_blank" rel="noreferrer">{title}</a><small>arXiv ↗</small></li>)}</ol></details><div className="pls-report-link"><div><span>WORKING PAPER</span><h3>Point–Line–Scene 完整研究报告</h3><p>保留 Capability Taxonomy、Schema、真实迁移记录、研究限制与附录。</p><Link className="paper-link" href="/audio-world-framework">早期研究笔记</Link></div><Link className="btn btn-primary" href="/point-line-scene-framework/report/">阅读完整报告</Link></div></div></section>
  <footer className="t2a-footer t2a-shell"><Link href="/">← 返回作品集</Link><Link href="/t2a-case-study">T2A 评测</Link><Link href="/audio-visual-evaluation">音视频生成评测</Link><Link href="/point-line-scene-framework/report/">完整报告</Link><span>© 2026 杜明</span></footer>
</main>; }
