import type { Metadata } from "next";
import Link from "next/link";
import "../t2a-case-study/t2a-case-study.css";
import "./point-line-scene-framework.css";
import { evaluationSystemEvidence, publicEvidenceStatusLabels } from "../../src/data/evaluation-system-evidence";

export const metadata: Metadata = {
  title: "PLS-Eval｜Point–Line–Scene 结构化诊断评测",
  description: "PLS-Eval 将生成任务拆成 Point、Line、Scene 三层可验证约束，并以独立 Quality 轴、参考链和单元级记录定位可观察失败。",
  keywords: ["PLS-Eval", "Point-Line-Scene", "Failure Localization", "Dependency-aware Evaluation", "Reference-aware Diagnosis", "生成式音频评测"],
  alternates: { canonical: "/point-line-scene-framework" },
};

const layers = [
  ["POINT", "点：局部事实", "Local / Atomic", "事件、声源、属性、材质、计数"],
  ["LINE", "线：事实关系", "Relational", "时间、空间、因果、交互、动态 / 声画同步"],
  ["SCENE", "面：整体场景", "Graph-level", "环境、层级、语境、显著性、整体一致性"],
] as const;

const evaluationStates = [
  ["PASS ✓", "有资格评价，满足要求", "pass"], ["PARTIAL ◐", "有资格评价，部分满足", "partial"],
  ["FAIL ×", "有资格评价，明确不满足", "fail"], ["BLOCKED ⊘", "前置条件失败，无法独立评价", "blocked"],
  ["N/A —", "当前任务从设计上不适用", "na"], ["SKIPPED", "具备资格，但本次未完成评分", "skipped"],
] as const;

const regressionCases = [
  ["Exact-count", "Repeated Diagnostic Pattern", "3→4→4 在 3 个可精确判定案例中重复出现。"],
  ["Onset", "Not Replicated", "Round-2 未复现 audio_early。"],
  ["Dynamic", "Mixed / Refined", "有边界响应，但连续 source-motion 跟随不足。"],
  ["Cross-shot", "Not Replicated", "未支持一般化的 Cut→Audio Loss 解释。"],
] as const;

const judgeAudit = [
  ["Detection", "Failure Recall · Balanced Accuracy"], ["Localization", "Exact Set Match · Failure Jaccard"],
  ["Decoupling", "Prediction Correlation · Pseudo-Decoupling"], ["Reliability", "Human Agreement · Domain Stability"],
] as const;

const frontierPapers = [
  ["OmniJudge", "Schema / Judge Audit", "保留分离维度，并审计失败发现能力。", "FUTURE INPUT", "https://arxiv.org/abs/2608.24160"],
  ["Voice-Agent Judge", "Evaluator Deployment", "按单元验证自动评测的可靠性。", "FUTURE INPUT", "https://arxiv.org/abs/2608.24314"],
  ["RubricRM", "Preference / Reward", "在固定 taxonomy 上研究任务相关偏好。", "FUTURE INPUT", "https://arxiv.org/abs/2608.26956"],
] as const;

const references = [
  ["AudioScape-TTA", "https://arxiv.org/abs/2608.04479"], ["AnyAudio-Judge", "https://arxiv.org/abs/2606.03116"], ["Fine-Grained Feedback for TTA", "https://arxiv.org/abs/2607.13408"],
  ["MMAG", "https://arxiv.org/abs/2608.06900"], ["AcoustiTrace", "https://arxiv.org/abs/2608.02035"], ["AVGen-Bench", "https://arxiv.org/abs/2604.08540"],
  ["Production-Oriented SFX Evaluation", "https://arxiv.org/abs/2607.09973"], ["AudioRubrics", "https://arxiv.org/abs/2608.02831"], ["LALM Judge Audit", "https://arxiv.org/abs/2607.13477"],
  ["OmniJudge or OmniBias? D³-Omni", "https://arxiv.org/abs/2608.24160"], ["Benchmarking LLM Judges for Voice-Agent Evaluation", "https://arxiv.org/abs/2608.24314"], ["RubricRM", "https://arxiv.org/abs/2608.26956"],
] as const;

function Arrow({ className = "" }: { className?: string }) { return <span className={`pls-v21-arrow ${className}`} aria-hidden="true" />; }
function SectionHeading({ index, title, children }: { index: string; title: string; children?: React.ReactNode }) { return <header className="pls-v21-heading"><p>{index}</p><h2>{title}</h2>{children && <div>{children}</div>}</header>; }

export default function PointLineSceneFrameworkPage() {
  return <main className="t2a-page pls-page pls-eval-page pls-v21-page">
    <header className="t2a-topbar"><Link className="wordmark" href="/" aria-label="返回作品集首页"><span className="wordmark-mark" aria-hidden="true" /><span>DU MING / AUDIO</span></Link><nav aria-label="PLS-Eval 页面导航"><Link className="topbar-mobile-only" href="/">首页</Link><a className="topbar-mobile-only" href="#dependency">依赖</a><a className="topbar-mobile-only" href="#reference">案例</a><a className="topbar-desktop-only" href="#framework">框架</a><a className="topbar-desktop-only" href="#dependency">依赖</a><a className="topbar-desktop-only" href="#reference">参考链</a><a className="topbar-desktop-only" href="#routing">路由</a><a className="topbar-desktop-only" href="#boundary">边界</a><a className="topbar-desktop-only" href="#research-details">文献</a></nav></header>

    <section className="pls-v21-hero t2a-shell"><div className="pls-v21-hero-copy"><p className="eyebrow">PLS-EVAL / METHOD</p><p className="pls-v21-kicker">Point–Line–Scene Structured Diagnostic Evaluation</p><h1>先定位失败原因，<br />再讨论整体分数</h1><p>PLS 不从“整体分数”开始，而从“哪一项要求在哪里失败”开始。Quality（质量）独立记录，不进入 P→L→S 的层级链。</p><div className="pls-v21-hero-actions"><a className="btn btn-primary" href="#framework">查看方法</a><Link className="paper-link" href="/point-line-scene-framework/report/">完整报告</Link></div></div><figure className="pls-v21-core-graph" role="img" aria-label="Requirement 分解为 Point、Line、Scene，得到单元级状态和失败定位；Quality 作为独立轴从侧面进入。"><div className="pls-v21-core-node is-root">REQUIREMENT</div><Arrow className="is-down" /><div className="pls-v21-core-branches"><div className="pls-v21-core-node">POINT<small>Local</small></div><div className="pls-v21-core-node">LINE<small>Relation</small></div><div className="pls-v21-core-node">SCENE<small>Global</small></div></div><Arrow className="is-down" /><div className="pls-v21-core-node is-state">UNIT-LEVEL STATE</div><Arrow className="is-down" /><div className="pls-v21-core-node is-output">FAILURE LOCALIZATION</div><div className="pls-v21-quality-rail"><span>QUALITY</span><small>Orthogonal axis</small></div><figcaption>PLS = 结构化任务要求，再定位可观察失败。</figcaption></figure></section>

    <section className="t2a-section t2a-shell" id="framework"><SectionHeading index="01 / PLS + QUALITY" title="三个约束层，外加一条独立质量轴"><p>Point、Line、Scene 分别检查事实、关系和场景；Quality 只描述输出自身质量。</p></SectionHeading><div className="pls-v21-layer-map" role="img" aria-label="Point、Line、Scene 三层约束与独立 Quality 质量轴">{layers.map(([id, title, type, items]) => <article key={id}><span>{id}</span><small>{type}</small><h3>{title}</h3><p>{items}</p></article>)}<aside><span>QUALITY</span><h3>独立质量轴</h3><p>Artifact · Noise · Clipping · Loudness · Spectral / Spatial Quality</p><strong>PLS + Q</strong></aside></div></section>

    <section className="t2a-section t2a-section-tint" id="schema"><div className="t2a-shell"><SectionHeading index="02 / STABLE TAXONOMY × DYNAMIC SCHEMA" title="固定坐标系，按任务激活评价单元"><p>已冻结的 P1–P4、L1–L4、S1–S4 不随 Prompt 改写；每条任务只激活适用单元。</p></SectionHeading><div className="pls-v21-schema-diagram" role="img" aria-label="稳定 taxonomy 在 prompt 激活后形成 active schema"><article><span>STABLE TAXONOMY</span><div className="pls-v21-taxonomy-dots"><b>P</b><b>P</b><b>P</b><b>P</b><b>L</b><b>L</b><b>L</b><b>L</b><b>S</b><b>S</b><b>S</b><b>S</b></div><small>12 项冻结 Capability</small></article><Arrow /><article><span>ACTIVE SCHEMA</span><p>“金属杯被敲三次，随后滑过木桌。”</p><div className="pls-v21-active-units"><b>P1 ●</b><b>P3 ●</b><b className="is-primary">P4 ● PRIMARY</b><b>L2 ●</b><b className="is-na">S1 ○ N/A</b></div></article></div><p className="pls-v21-principle">Ontology stays stable; applicable evaluation units change with the task.</p></div></section>

    <section className="t2a-section t2a-shell" id="atomic-units"><SectionHeading index="03 / ATOMIC EVALUATION UNIT" title="一个单元，只回答一个可证伪问题"><p>原子化使低分能回到具体要求，而不是把事件、材质、次数和顺序揉成一个结论。</p></SectionHeading><div className="pls-v21-atomic-compare"><article className="is-coupled"><span>COUPLED RUBRIC</span><h3>事件、材质、次数和顺序是否都正确？</h3><strong>FAIL ×</strong><p>无法识别哪项要求失败。</p></article><Arrow /><article className="is-decoupled"><span>DECOUPLED UNITS</span><div><b>P1 事件完整性 <i>5</i></b><b>P3 材质 / 属性 <i>5</i></b><b className="is-focus">P4 事件计数 <i>2</i></b><b>L2 时间顺序 <i>5</i></b></div><p>低分可直接回到 P4。</p></article></div></section>

    <section className="t2a-section t2a-section-tint" id="dependency"><div className="t2a-shell"><SectionHeading index="04 / DEPENDENCY-AWARE EVALUATION" title="原子化不等于无依赖"><p>评价单元保持原子化，但一个单元是否具备评价资格，可以依赖上游前置条件。</p></SectionHeading><div className="pls-v21-dependency-layout"><figure className="pls-v21-dag" role="img" aria-label="P2 依赖 P1；P4 依赖 P3；L1 同时依赖 P1 和 P3 的资格依赖图。"><figcaption>Three metallic knocks, followed by a wooden object sliding.</figcaption><div className="pls-v21-dag-grid"><article className="is-pass"><span>P1</span><strong>Metallic knock exists</strong><small>PASS ✓</small></article><article className="is-pass"><span>P2</span><strong>Count = 3</strong><small>PASS ✓</small></article><article className="is-fail"><span>P3</span><strong>Sliding event exists</strong><small>FAIL ×</small></article><article className="is-blocked"><span>P4</span><strong>Material = wooden</strong><small>BLOCKED ⊘</small></article><article className="is-blocked is-l1"><span>L1</span><strong>Knock before sliding</strong><small>BLOCKED ⊘</small></article><i className="edge edge-p1-p2" aria-hidden="true" /><i className="edge edge-p1-p3" aria-hidden="true" /><i className="edge edge-p3-p4" aria-hidden="true" /><i className="edge edge-p1-l1" aria-hidden="true" /><i className="edge edge-p3-l1" aria-hidden="true" /></div></figure><aside className="pls-v21-state-legend"><h3>Evaluation State</h3>{evaluationStates.map(([state, description, tone]) => <div key={state} className={`is-${tone}`}><strong>{state}</strong><span>{description}</span></div>)}<p>BLOCKED ≠ N/A ≠ SKIPPED</p></aside></div><p className="pls-v21-callout">一个 missing event 不应扩散成 material failure 和 temporal failure。</p><div className="pls-v21-outcome-split" role="img" aria-label="单元级 P2 失败、L1 阻断，与案例级 temporal order 前置条件失败的分离状态。"><article><span>UNIT-LEVEL ATTRIBUTION</span><div><b>P2 · Bird exists</b><strong>FAIL ×</strong></div><div><b>L1 · Temporal order</b><strong>BLOCKED ⊘</strong><small>blocked_by = P2</small></div></article><Arrow /><article className="is-case"><span>CASE-LEVEL OUTCOME</span><p>PRIMARY TARGET</p><b>TEMPORAL ORDER</b><strong>FAIL_PREREQUISITE</strong><small>下游 Unit 可以 BLOCKED，但 Case 仍然失败。</small></article></div></div></section>

    <section className="t2a-section t2a-shell" id="case-anatomy"><SectionHeading index="05 / PRIMARY TARGET + DIAGNOSTIC UNITS" title="主评测目标引导案例，其他适用单元保留为诊断项"><p>Focused diagnostic cases 通常有一个主评测目标；Integration Cases 可以有复合目标。</p></SectionHeading><div className="pls-v21-case-anatomy" role="img" aria-label="T2A_TEMP_007 的主评测目标是 Temporal Order，诊断项包括 Dog exists、Bird exists、Near far。"><article><span>CASE</span><strong>T2A_TEMP_007</strong><p>A dog barks nearby before a bird chirps in the distance.</p></article><Arrow /><article className="is-target"><span>PRIMARY TARGET</span><strong>Temporal<br />Order</strong><small>L1 · dog before bird</small></article><Arrow /><article className="is-diagnostics"><span>DIAGNOSTIC REQUIREMENTS</span><div><b>P1 · Dog exists</b><b>P2 · Bird exists</b><b>L2 · Near / Far</b></div><small>Near / far 属于 Line，不属于 Scene。</small></article></div></section>

    <section className="t2a-section t2a-section-tint" id="metrics"><div className="t2a-shell"><SectionHeading index="06 / CONDITIONAL VS END-TO-END" title="同时报告资格、条件准确率与端到端成功"><p>Conditional Accuracy 只解释前置条件成立后的能力；End-to-End Success 保留实际任务完成情况。</p></SectionHeading><figure className="pls-v21-metric-flow" role="img" aria-label="100 个 Temporal cases 中，15 个前置条件失败，85 个可评价；可评价案例中 68 个顺序正确，17 个顺序错误。"><div className="pls-v21-metric-root"><strong>100</strong><span>Designed Cases</span></div><div className="pls-v21-metric-branches"><div className="is-fail"><strong>15</strong><span>Prerequisite Failure</span></div><div className="is-pass"><strong>85</strong><span>Eligible</span><div><b>68 · Order Correct</b><b>17 · Order Wrong</b></div></div></div></figure><div className="pls-v21-metric-tiles"><article><strong>85%</strong><span>Prerequisite Satisfaction</span><small>85 / 100</small></article><article><strong>80%</strong><span>Conditional Temporal Accuracy</span><small>68 / 85</small></article><article><strong>68%</strong><span>End-to-End Temporal Success</span><small>68 / 100</small></article></div></div></section>

    <section className="pls-v21-reference-band" id="reference"><div className="t2a-shell"><SectionHeading index="07 / REFERENCE-AWARE DIAGNOSIS" title="3→4→4：比较哪一段参考链，决定问题归因"><p>P06、P10 与 R2-H1-B 在两轮中形成可精确判定的 Repeated Diagnostic Pattern。</p></SectionHeading><div className="pls-v21-reference-chain" role="img" aria-label="Prompt count 3 到 Visual count 4 是 instruction fidelity fail，Visual count 4 到 Audio count 4 是 event correspondence pass。"><article><span>PROMPT</span><strong>3</strong><small>COUNT = 3</small></article><div className="pls-v21-reference-edge is-fail"><Arrow /><b>Instruction Fidelity<br />FAIL ×</b></div><article className="is-fail"><span>VISUAL</span><strong>4</strong><small>COUNT = 4</small></article><div className="pls-v21-reference-edge is-pass"><Arrow /><b>Event Correspondence<br />PASS ✓</b></div><article className="is-pass"><span>AUDIO</span><strong>4</strong><small>COUNT = 4</small></article></div><div className="pls-v21-attribution-compare"><div><span>WITHOUT REFERENCE CHAIN</span><strong>Audio Counting Failure <b>×</b></strong></div><div><span>WITH REFERENCE CHAIN</span><strong>Visual Instruction Failure <b>✓</b></strong></div></div><div className="pls-v21-case-links"><Link className="btn btn-primary" href="/audio-visual-evaluation">查看两轮音视频评测</Link><span>Evidence status · Repeated Diagnostic Pattern</span></div></div></section>

    <section className="t2a-section t2a-shell" id="unit-record"><SectionHeading index="08 / UNIT-LEVEL RECORD" title="原始单元状态在前，聚合展示在后"><p>单元级记录保留 Capability、参考关系、Bad Case 与独立质量；Point / Line 均值只是派生视图。</p></SectionHeading><div className="pls-v21-record-flow"><article><span>RAW STATE · P06</span><div><b>P4 Event Counting <i>5 / 5</i></b><b>L1 Onset Alignment <i>3 / 5</i></b><b>Instruction Fidelity <i className="is-fail">FAIL ×</i></b><b>Cross-modal Correspondence <i className="is-pass">PASS ✓</i></b><b>OVL <i>4 / 5</i></b></div><small><code>audio_early</code> remains observable.</small></article><Arrow /><article className="is-derived"><span>DERIVED VIEW</span><div><b>Point <i>5.00</i></b><b>Line <i>4.00</i></b><b>OVL <i>4 / 5</i></b></div><small>聚合不能反向覆盖 Facts 或 Bad Case。</small></article></div><div className="pls-v21-quality-proof"><span>H2 · RELATION CORRECTNESS</span><strong>Point 5.00 / Line 5.00</strong><b>≠</b><span>PERCEPTUAL QUALITY</span><strong>OVL 3 · <code>loudness_imbalance</code></strong><p>关系正确，输出质量仍可较低。</p></div></section>

    <section className="t2a-section t2a-section-tint" id="routing"><div className="t2a-shell"><SectionHeading index="09 / EVALUATOR ROUTING" title="不同单元，匹配不同证据来源"><p>当前路由是 Human + Signal + structured execution；Audio / Omni Judge 仍是 Future Validation。</p></SectionHeading><figure className="pls-v21-routing-graph" role="img" aria-label="一个原子评价单元可由 Human、Signal 或 Future Judge 评估，汇聚成单元级状态。"><div>ATOMIC UNIT</div><Arrow className="is-down" /><section><article>HUMAN<small>Scene coherence</small></article><article>SIGNAL<small>AV offset · clipping</small></article><article className="is-future">JUDGE<small>FUTURE / NOT IMPLEMENTED</small></article></section><Arrow className="is-down" /><div>UNIT STATE</div></figure><div className="pls-v21-routing-examples"><b>AV Offset <span>→ Timestamp / Signal</span></b><b>Artifact / Clipping <span>→ Signal + Human</span></b><b>Scene Coherence <span>→ Human</span></b><b>Audio / Omni Judge <span>→ Future Validation</span></b></div></div></section>

    <section className="t2a-section t2a-shell" id="drill-down"><SectionHeading index="10 / OBSERVABLE FAILURE LOCALIZATION" title="从回归信号下钻到可观察证据"><p>这条链定位的是评测对象与可观察失败，不主张没有模型 traces 的内部因果。</p></SectionHeading><div className="pls-v21-drilldown" role="img" aria-label="模型回归从 capability 下钻到 unit、case、observable evidence、failure label、regression action。"><div className="pls-v21-drill-chain">{["MODEL REGRESSION", "CAPABILITY · P / L / S / Q", "UNIT", "CASE", "OBSERVABLE EVIDENCE", "FAILURE LABEL", "REGRESSION ACTION"].map((item, index) => <span key={item}>{index > 0 && <Arrow className="is-down" />}<b>{item}</b></span>)}</div><article><span>EXAMPLE</span><p>REL ↓</p><b>Multi-event → Point → Secondary Event Recall</b><code>missing_secondary_event</code><strong>Regression Set</strong></article></div><p className="pls-v21-boundary-tag">No internal causal claim without model traces.</p></section>

    <section className="t2a-section t2a-section-tint" id="regression"><div className="t2a-shell"><SectionHeading index="11 / CONTROLLED REGRESSION" title="发现失败后，用新样本检查是否重现"><p>Round-1 负责发现；Round-2 在生成前冻结假设、观察字段和判定规则，再更新后续排查优先级。</p></SectionHeading><div className="pls-v21-regression-diff" role="img" aria-label="模型版本通过 regression suite 比较证据状态；这些是跨轮证据状态，不是总体性能数值差异。"><div><b>MODEL v1</b><Arrow className="is-down" /><strong>Regression Suite</strong><Arrow className="is-down" /><b>MODEL v2</b></div><section>{regressionCases.map(([probe, status, detail]) => <article key={probe}><span>{probe}</span><strong>{status}</strong><small>{detail}</small></article>)}</section></div><p className="pls-v21-fineprint">展示的是跨轮证据状态，不是总体性能增减或统计显著性结论。</p></div></section>

    <section className="t2a-section t2a-shell" id="judge-audit"><SectionHeading index="12 / JUDGE AUDIT · FUTURE" title="总体准确率不等于失败定位能力"><p>Judge 进入正式评分链路前，需单独审计 Detection、Localization、Decoupling 与 Reliability。</p></SectionHeading><div className="pls-v21-audit-matrix">{judgeAudit.map(([title, metric]) => <article key={title}><h3>{title}</h3><p>{metric}</p><span>FUTURE / NOT IMPLEMENTED</span></article>)}</div><div className="pls-v21-localization-proof"><strong>85%<small>AGGREGATE ACCURACY</small></strong><b>≠</b><article><span>GT {`{P3, L2}`}</span><span>Judge {`{P3, L2}`}</span><strong>Exact Localization ✓</strong></article></div></section>

    <section className="t2a-section t2a-section-tint" id="boundary"><div className="t2a-shell"><SectionHeading index="13 / EVIDENCE BOUNDARY" title="区分已实现、方法扩展与未来研究"><p>页面用真实案例说明现有证据，也明确不做超过样本和执行范围的主张。</p></SectionHeading><div className="pls-v21-boundary-grid"><article><span>IMPLEMENTED</span><p>PLS Schema · Human Evaluation · Signal Diagnostics · Reference-aware Diagnosis · Unit Record · Controlled Regression</p></article><article><span>METHOD EXTENSION</span><p>Dependency-aware Eligibility · BLOCKED semantics · Primary Target + Diagnostic Units · Conditional / End-to-End separation</p></article><article><span>FUTURE</span><p>Audio / Omni Judge · Judge Reliability Benchmark · Dynamic Importance · Pairwise Preference · Reward Model</p></article></div><p className="pls-v21-limitation"><strong>当前证据：</strong>Round-1 10 个、Round-2 6 个单次生成；不构成 multi-seed statistical experiment，也不做总体性能泛化。</p></div></section>

    <section className="t2a-section t2a-shell" id="research-details"><SectionHeading index="RESEARCH DETAILS" title="研究来源与完整材料"><p>研究脉络收进折叠区；主体页面优先解释方法、案例、边界与可观察证据。</p></SectionHeading><div className="pls-v21-frontier">{frontierPapers.map(([title, theme, influence, label, href]) => <article key={title}><span>{theme}</span><h3>{title}</h3><p>{influence}</p><b>{label}</b><a href={href} target="_blank" rel="noreferrer">阅读论文 ↗</a></article>)}</div><details className="pls-landing-details"><summary>展开已执行的 Signal Diagnostics 指标</summary><div className="pls-v21-signal-details"><div>{evaluationSystemEvidence.systemStatuses.map((item) => <article key={item.label}><span>{publicEvidenceStatusLabels[item.status]}</span><strong>{item.label}</strong></article>)}</div><p>{evaluationSystemEvidence.publicBoundary}</p></div></details><details className="pls-landing-details"><summary>展开 12 条参考文献</summary><ol className="pls-reference-list">{references.map(([title, href]) => <li key={href}><a href={href} target="_blank" rel="noreferrer">{title}</a><small>arXiv ↗</small></li>)}</ol></details><div className="pls-report-link"><div><span>WORKING PAPER</span><h3>Point–Line–Scene 完整研究报告</h3><p>保留 Capability Taxonomy、Schema、真实迁移记录、研究限制与附录。</p><Link className="paper-link" href="/audio-world-framework">早期研究笔记</Link></div><Link className="btn btn-primary" href="/point-line-scene-framework/report/">阅读完整报告</Link></div></section>
    <footer className="t2a-footer t2a-shell"><Link href="/">← 返回作品集</Link><Link href="/t2a-case-study">T2A 评测</Link><Link href="/audio-visual-evaluation">音视频生成评测</Link><Link href="/point-line-scene-framework/report/">完整报告</Link><span>© 2026 杜明</span></footer>
  </main>;
}
