import type { Metadata } from "next";
import Link from "next/link";
import "../t2a-case-study/t2a-case-study.css";
import "./point-line-scene-framework.css";
import "./evidence-integrity.css";
import { evaluationSystemEvidence, publicEvidenceStatusLabels } from "../../src/data/evaluation-system-evidence";

export const metadata: Metadata = {
  title: "PLS-Eval｜Point–Line–Scene 结构化诊断评测",
  description: "PLS-Eval 将生成任务拆成 Point、Line、Scene 三层可验证约束，并以独立 Quality 轴、显式参考链与单元级记录定位可观察失败。",
  keywords: ["PLS-Eval", "Point-Line-Scene", "Failure Localization", "Reference-aware Diagnosis", "生成式音频评测"],
  alternates: { canonical: "/point-line-scene-framework" },
};

const layers = [["POINT", "点：局部事实", "局部 / 原子", "事件 · 声源 · 属性 · 材质 · 计数"], ["LINE", "线：事实关系", "关系", "时间 · 空间 · 因果 · 交互 · 动态 / 声画同步"], ["SCENE", "面：整体场景", "整体 / 场景级", "环境 · 层级 · 语境 · 显著性 · 整体一致性"]] as const;
const regressionCases = [["精确计数", "重复诊断模式", "Repeated Diagnostic Pattern", "3→4→4 在 3 个可精确判定案例中重复出现。"], ["起点对齐", "未复现", "Not Replicated", "Round-2 未复现 audio_early。"], ["动态对应", "部分成立 / 需细化", "Mixed / Refined", "有边界响应，但连续 source-motion 跟随不足。"], ["跨镜头持续性", "未复现", "Not Replicated", "未支持一般化的 Cut→Audio Loss 解释。"]] as const;
const judgeAudit = [["失败发现", "Detection", "失败召回率 · 平衡准确率"], ["失败定位", "Localization", "失败集合完全匹配 · Jaccard"], ["解耦检查", "Decoupling", "预测相关性 · 伪解耦检查"], ["可靠性", "Reliability", "人类评测一致性 · 跨域稳定性"]] as const;
const frontierPapers = [["OmniJudge", "结构设计与 Judge 审计", "保留分离维度，并审计失败发现能力。", "未来研究输入", "https://arxiv.org/abs/2608.24160"], ["Voice-Agent Judge", "评测器部署", "按单元验证自动评测的可靠性。", "未来研究输入", "https://arxiv.org/abs/2608.24314"], ["RubricRM", "偏好与奖励", "在固定 taxonomy 上研究任务相关偏好。", "未来研究输入", "https://arxiv.org/abs/2608.26956"]] as const;
const references = [["AudioScape-TTA", "https://arxiv.org/abs/2608.04479"], ["AnyAudio-Judge", "https://arxiv.org/abs/2606.03116"], ["Fine-Grained Feedback for TTA", "https://arxiv.org/abs/2607.13408"], ["MMAG", "https://arxiv.org/abs/2608.06900"], ["AcoustiTrace", "https://arxiv.org/abs/2608.02035"], ["AVGen-Bench", "https://arxiv.org/abs/2604.08540"], ["Production-Oriented SFX Evaluation", "https://arxiv.org/abs/2607.09973"], ["AudioRubrics", "https://arxiv.org/abs/2608.02831"], ["LALM Judge Audit", "https://arxiv.org/abs/2607.13477"], ["OmniJudge or OmniBias? D³-Omni", "https://arxiv.org/abs/2608.24160"], ["Benchmarking LLM Judges for Voice-Agent Evaluation", "https://arxiv.org/abs/2608.24314"], ["RubricRM", "https://arxiv.org/abs/2608.26956"]] as const;
function Arrow({ down = false }: { down?: boolean }) { return <span className={`pls-v21-arrow ${down ? "is-down" : ""}`} aria-hidden="true" />; }
function Heading({ index, title, children }: { index: string; title: string; children?: React.ReactNode }) { return <header className="pls-v21-heading"><p>{index}</p><h2>{title}</h2>{children && <div>{children}</div>}</header>; }

export default function PointLineSceneFrameworkPage() { return <main className="t2a-page pls-page pls-eval-page pls-v21-page">
  <header className="t2a-topbar"><Link className="wordmark" href="/" aria-label="返回作品集首页"><span className="wordmark-mark" aria-hidden="true" /><span>DU MING / AUDIO</span></Link><nav aria-label="PLS-Eval 页面导航"><Link className="topbar-mobile-only" href="/">首页</Link><a className="topbar-mobile-only" href="#reference">案例</a><a className="topbar-desktop-only" href="#framework">框架</a><a className="topbar-desktop-only" href="#reference">参考链</a><a className="topbar-desktop-only" href="#regression">回归</a><a className="topbar-desktop-only" href="#evidence-roles">证据</a><a className="topbar-desktop-only" href="#boundary">边界</a><a className="topbar-desktop-only" href="#research-details">文献</a></nav></header>

  <section className="pls-v21-hero t2a-shell"><div className="pls-v21-hero-copy"><p className="eyebrow">PLS-Eval / 结构化评测</p><p className="pls-v21-kicker">Point–Line–Scene Structured Diagnostic Evaluation</p><h1>先定位失败原因，<br />再讨论整体分数</h1><p>PLS 不从“整体分数”开始，而从“哪一项要求在哪里失败”开始。Quality（质量）独立记录，不进入 P→L→S 的层级链。</p><div className="pls-v21-hero-actions"><a className="btn btn-primary" href="#reference">查看真实案例</a><Link className="paper-link" href="/point-line-scene-framework/report/">完整报告</Link></div></div><figure className="pls-v21-core-graph" role="img" aria-label="任务要求分解为点、线、面，得到单元级记录和失败定位；质量作为独立轴从侧面进入。"><div className="pls-v21-core-node is-root">任务要求<small>Requirement</small></div><Arrow down /><div className="pls-v21-core-branches"><div className="pls-v21-core-node">点<small>POINT · 局部事实</small></div><div className="pls-v21-core-node">线<small>LINE · 关系</small></div><div className="pls-v21-core-node">面<small>SCENE · 整体场景</small></div></div><Arrow down /><div className="pls-v21-core-node is-state">单元级记录<small>Unit-level Record</small></div><Arrow down /><div className="pls-v21-core-node is-output">失败定位<small>Failure Localization</small></div><div className="pls-v21-quality-rail"><span>独立质量</span><small>Quality · 独立记录</small></div><figcaption>PLS = 结构化任务要求，再定位可观察失败项。</figcaption></figure></section>

  <section className="t2a-section t2a-shell" id="framework"><Heading index="01 / PLS + 独立质量" title="三个约束层，外加一条独立质量轴"><p>Point、Line、Scene 分别检查事实、关系和场景；Quality 只描述输出自身质量。</p></Heading><div className="pls-v21-layer-map" role="img" aria-label="Point、Line、Scene 三层约束与独立 Quality 质量轴">{layers.map(([id, title, type, items]) => <article key={id}><h3>{title}</h3><span>{id}</span><small>{type}</small><p>{items}</p></article>)}<aside><h3>独立质量轴</h3><span>QUALITY</span><p>伪影 · 噪声 · 削波 · 响度 · 频谱 / 空间质量</p><strong>PLS + Q</strong></aside></div></section>

  <section className="t2a-section t2a-section-tint" id="schema"><div className="t2a-shell"><Heading index="02 / 固定能力分类 × 按任务激活" title="固定坐标系，按任务激活评价单元"><p>已冻结的 P1–P4、L1–L4、S1–S4 不随 Prompt 改写；每条任务只激活适用单元。</p></Heading><div className="pls-v21-schema-diagram" role="img" aria-label="固定能力分类按任务要求形成当前激活项"><article><h3>固定能力分类</h3><span>Stable Taxonomy</span><div className="pls-v21-taxonomy-dots">{["P","P","P","P","L","L","L","L","S","S","S","S"].map((item, index) => <b key={`${item}-${index}`}>{item}</b>)}</div><small>12 项冻结能力</small></article><Arrow /><article><h3>当前任务激活项</h3><span>Active Schema</span><p>“金属杯被敲三次，随后滑过木桌。”</p><div className="pls-v21-active-units"><b>P1 ●</b><b>P3 ●</b><b>P4 ●</b><b>L2 ●</b><b className="is-na">S1 ○ 不适用 <small>N/A</small></b></div></article></div><p className="pls-v21-principle">能力分类保持稳定，具体评价单元按任务要求激活。</p></div></section>

  <section className="t2a-section t2a-shell" id="atomic-units"><Heading index="03 / 原子评价单元" title="一个单元，只验证一个问题"><p>原子化让每个要求都可单独检查；它不代表预设一组示例分数。</p></Heading><div className="pls-v21-atomic-compare"><article className="is-coupled"><h3>耦合式评分</h3><span>Coupled Rubric</span><p className="pls-v21-atomic-sequence">事件 + 材质 + 次数 + 顺序<br />↓<br /><strong>一个结果：失败 ×</strong></p><p>无法定位具体失败项。</p></article><Arrow /><article className="is-decoupled"><h3>拆分后的评价单元</h3><span>Atomic Units</span><div><b>事件</b><b>材质</b><b>次数</b><b>时间顺序</b></div><p>分别进入单元级记录。</p></article></div></section>

  <section className="pls-v21-reference-band" id="reference"><div className="t2a-shell"><Heading index="04 / 显式参考链诊断 · 案例支持" title="3→4→4：比较哪一段参考链，决定问题归因"><p>P06、P10 与 R2-H1-B 在两轮中形成可精确判定的重复诊断模式（Repeated Diagnostic Pattern）。</p></Heading><div className="pls-v21-reference-chain" role="img" aria-label="文本要求 3 次到画面事实 4 次是指令符合度失败，画面事实 4 次到音频事件 4 次是事件对应通过。"><article><span>文本要求<small>Prompt</small></span><strong>3</strong><small>要求 3 次</small></article><div className="pls-v21-reference-edge is-fail"><Arrow /><b>指令符合度<small>Instruction Fidelity</small><br />× 失败</b></div><article className="is-fail"><span>画面事实<small>Visual</small></span><strong>4</strong><small>实际 4 次</small></article><div className="pls-v21-reference-edge is-pass"><Arrow /><b>事件对应<small>Event Correspondence</small><br />✓ 通过</b></div><article className="is-pass"><span>音频事件<small>Audio</small></span><strong>4</strong><small>实际 4 次</small></article></div><div className="pls-v21-attribution-compare"><div><span>不区分参考链</span><strong>× 误归因：音频计数失败</strong></div><div><span>区分参考链</span><strong>✓ 定位：文本 → 画面数量约束失败</strong></div></div><div className="pls-v21-case-links"><Link className="btn btn-primary" href="/audio-visual-evaluation">查看两轮音视频评测</Link><span>证据状态：重复诊断模式 <small>Repeated Diagnostic Pattern</small></span></div></div></section>

  <section className="t2a-section t2a-shell" id="unit-record"><Heading index="05 / 单元级记录 · 已实现" title="原始单元状态在前，聚合展示在后"><p>P06 记录保留能力项、参考关系、失败案例（Bad Case）与独立质量；Point / Line 均值只是派生视图。</p></Heading><div className="pls-v21-record-flow"><article><span>P06 · 原始记录 <small>Raw Record</small></span><div><b>P4 事件计数 <small>Event Counting</small><i>5 / 5</i></b><b>L1 起点对齐 <small>Onset Alignment</small><i>3 / 5</i></b><b>指令符合度 <small>Instruction Fidelity</small><i className="is-fail">失败 ×</i></b><b>跨模态对应 <small>Cross-modal Correspondence</small><i className="is-pass">通过 ✓</i></b><b>独立质量 OVL <i>4 / 5</i></b></div><small><code>audio_early</code> 仍保留在记录中。</small></article><Arrow /><article className="is-derived"><span>派生视图 <small>Derived View</small></span><div><b>Point <i>5.00</i></b><b>Line <i>4.00</i></b><b>OVL <i>4 / 5</i></b></div><small>聚合不能反向覆盖事实或失败案例。</small></article></div><div className="pls-v21-quality-proof"><span>关系正确性 <small>Relational Correctness</small></span><strong>Point 5.00 / Line 5.00</strong><b>≠</b><span>感知质量 <small>Perceptual Quality</small></span><strong>OVL 3 · <code>loudness_imbalance</code></strong><p>关系正确，输出质量仍可较低。</p></div></section>

  <section className="t2a-section t2a-section-tint" id="regression"><div className="t2a-shell"><Heading index="06 / 受控回归 · 已执行" title="发现失败后，用新样本检查是否重现"><p>Round-1 负责发现；Round-2 在生成前冻结假设、观察字段和判定规则，再更新后续排查优先级。</p></Heading><div className="pls-v21-regression-diff"><div><b>第一轮 <small>Round-1</small></b><Arrow down /><strong>受控回归 <small>Controlled Regression</small></strong><Arrow down /><b>第二轮 <small>Round-2</small></b></div><section>{regressionCases.map(([probe, status, alias, detail]) => <article key={probe}><span>{probe}</span><strong>{status}</strong><em>{alias}</em><small>{detail}</small></article>)}</section></div><div className="pls-v21-real-drilldown" role="img" aria-label="从 3→4→4 重复观察到精确计数回归优先级的真实证据链。"><div>{["重复观察 · 3→4→4", "能力 / 参考关系 · 精确计数 · P4", "涉及案例 · P06 · P10 · R2-H1-B", "可观察事实 · Prompt 3 · Visual 4 · Audio 4", "问题定位 · 文本→画面不一致；画面→音频计数一致", "下一步 · 提高精确计数回归优先级"].map((item, index) => <span key={item}>{index > 0 && <Arrow down />}<b>{item}</b></span>)}</div></div></div></section>

  <section className="t2a-section t2a-shell" id="evidence-roles"><Heading index="07 / 证据分工" title="评测证据如何分工"><p>人工判断、信号诊断与结构化执行承担不同职责；它们不是一个自动路由系统。</p></Heading><div className="pls-v21-evidence-architecture" role="img" aria-label="人工评测进入评测记录和执行层；信号诊断作为独立辅助证据，模型 Judge 属于后续扩展。"><div className="pls-v21-human-lane"><span>主判断</span><article><b>人工评测</b><em>Human Evaluation</em><small>已实现</small><p>画面事实 · PLS 能力评分 · OVL · 失败案例（Bad Case）</p></article><Arrow down /><article><b>评测记录</b><em>Evaluation Record</em><small>已实现</small><p>事实 · 评分 · 参考关系 · 标签</p></article><Arrow down /><article><b>执行层 v0.1</b><em>Execution Layer</em><small>已实现</small><p>结构校验 · 维度概况 · 诊断摘要</p></article></div><aside><span>辅助证据</span><article className="is-signal"><b>信号诊断</b><em>Signal Diagnostics</em><small>已实现</small><p>文件 / 技术 · 频谱 · 空间 · 动态</p></article><p className="pls-v21-concept-link">人工对照<br />概念整合</p><article className="is-future"><b>模型评测器</b><em>Model Judge</em><small>后续扩展</small><p>尚未实现 · 需要可靠性验证</p></article></aside></div><p className="pls-v21-evidence-note">Signal Diagnostics 不自动生成或修改 PLS / OVL 评分；当前由人工分析进行对照。</p></section>

  <section className="t2a-section t2a-section-tint" id="boundary"><div className="t2a-shell"><Heading index="08 / 证据边界" title="用四级状态区分证据与方向"><p>主体展示真实执行或案例支持的结果；尚未回填到冻结数据的设计单独标记。</p></Heading><div className="pls-v21-boundary-grid pls-v21-boundary-grid-four"><article><span>已实现 <small>IMPLEMENTED</small></span><p>PLS 能力分类与 Schema v1.0 · 人工评测 · 信号诊断批量分析 · 执行层 v0.1 · 单元级记录 · 受控回归</p></article><article><span>案例支持 <small>CASE-SUPPORTED</small></span><p>3→4→4 显式参考链诊断 · 精确计数重复模式 · 起点对齐：未复现 · 动态对应：部分成立 / 需细化 · 跨镜头持续性：未复现 · 关系正确 ≠ 感知质量</p></article><article><span>概念整合 <small>INTEGRATED CONCEPT</small></span><p>信号证据与 PLS 记录连接 · 依赖感知的评价资格 · BLOCKED 状态设计 · 主目标案例设计<br /><small>未完全执行 / 未回填</small></p></article><article><span>未来扩展 <small>FUTURE EXTENSION</small></span><p>音频 / 全模态评测器 · 多评测员校准 · 偏好建模 · 动态重要度 · 奖励模型（Reward Model）</p></article></div><p className="pls-v21-limitation"><strong>当前证据：</strong>Round-1 10 个、Round-2 6 个单次生成；不构成多随机种子统计实验（multi-seed statistical experiment），也不做总体性能泛化。</p></div></section>

  <section className="t2a-section t2a-shell" id="method-extensions"><Heading index="09 / 方法扩展" title="尚未应用到冻结数据的方法设计"><p>下列内容不作为当前项目结果，也未回填至原始数据集。</p></Heading><details className="pls-landing-details"><summary>展开尚未应用到冻结数据的方法设计</summary><div className="pls-v21-extension-grid"><article><span>依赖感知的评价资格 <small>DEPENDENCY-AWARE ELIGIBILITY</small></span><h3>先判断是否具备评价条件</h3><p>若事件存在，则继续评价属性；若事件缺失，下游属性或关系记为 BLOCKED。</p><small>建议状态逻辑 · 尚未应用</small></article><article><span>主目标 + 诊断单元 <small>PRIMARY TARGET + DIAGNOSTIC UNITS</small></span><h3>未来案例设计</h3><p>后续专项案例可指定一个主目标（Primary Target），同时保留其他适用要求作为诊断单元（Diagnostic Units）。</p><small>未来数据集设计 · 尚未回填</small></article><article><span>未来指标设计 <small>FUTURE METRIC DESIGN</small></span><h3>资格与成功率公式</h3><p>评价资格率 = 可评价项 / 设计项<br />条件准确率 = 正确项 / 可评价项<br />端到端成功率 = 正确项 / 设计项</p><small>仅为公式设计 · 无项目结果</small></article></div></details></section>

  <section className="t2a-section t2a-section-tint" id="research-details"><div className="t2a-shell"><Heading index="10 / 研究前沿 · 未来" title="研究来源与未来评测"><p>文献启发后续模型评测器、偏好与奖励研究，不构成当前项目已部署能力。</p></Heading><div className="pls-v21-frontier">{frontierPapers.map(([title, theme, influence, label, href]) => <article key={title}><span>{theme}</span><h3>{title}</h3><p>{influence}</p><b>{label}</b><a href={href} target="_blank" rel="noreferrer">阅读论文 ↗</a></article>)}</div><details className="pls-landing-details"><summary>展开评测器审计（Judge Audit）· 文献启发，未在本项目测量</summary><div className="pls-v21-audit-matrix">{judgeAudit.map(([title, alias, metric]) => <article key={title}><h3>{title}</h3><em>{alias}</em><p>{metric}</p><span>后续扩展 · 尚未实现</span></article>)}</div><div className="pls-v21-judge-concept"><strong>总体准确率</strong><b>≠</b><strong>精确失败定位</strong></div></details><details className="pls-landing-details"><summary>展开已执行的信号诊断（Signal Diagnostics）指标</summary><div className="pls-v21-signal-details"><div>{evaluationSystemEvidence.systemStatuses.map((item) => <article key={item.label}><span>{publicEvidenceStatusLabels[item.status]}</span><strong>{item.label}</strong></article>)}</div><p>{evaluationSystemEvidence.publicBoundary}</p></div></details><details className="pls-landing-details"><summary>展开 12 条参考文献</summary><ol className="pls-reference-list">{references.map(([title, href]) => <li key={href}><a href={href} target="_blank" rel="noreferrer">{title}</a><small>arXiv ↗</small></li>)}</ol></details><div className="pls-report-link"><div><span>研究报告 <small>WORKING PAPER</small></span><h3>点—线—面（Point–Line–Scene）完整研究报告</h3><p>保留能力分类（Capability Taxonomy）、Schema、真实迁移记录、研究限制与附录。</p><Link className="paper-link" href="/audio-world-framework">早期研究笔记</Link></div><Link className="btn btn-primary" href="/point-line-scene-framework/report/">阅读完整报告</Link></div></div></section>
  <footer className="t2a-footer t2a-shell"><Link href="/">← 返回作品集</Link><Link href="/t2a-case-study">T2A 评测</Link><Link href="/audio-visual-evaluation">音视频生成评测</Link><Link href="/point-line-scene-framework/report/">完整报告</Link><span>© 2026 杜明</span></footer>
</main>; }
