import Link from 'next/link';
import trace from './trace.json';
import type { Metadata } from 'next';
import './case-study.css';

export const metadata: Metadata = { title: 'Creative QC & Repair Agent | Du Ming', description: 'An evaluated multimodal creative Agent prototype for requirement compilation, tool planning, automatic QC, failure localization and targeted repair.', alternates: { canonical: '/creative-qc-agent/' }, openGraph: { title: 'Creative QC & Repair Agent | Du Ming', description: '需求编译、工具规划、自动质检与定向修复 Agent 原型', url: 'https://ventusdu0809.github.io/creative-qc-agent/' } };
const base = '/assets/creative-qc-agent';
function Film({ name, label, chapters = false }: { name: string; label: string; chapters?: boolean }) {
 return <div className="cs-film"><video controls playsInline preload="metadata" poster={`${base}/media/${name}-poster.jpg`} aria-label={label}><source src={`${base}/media/${name === "a10-repair" ? "a03" : name}.mp4`} type="video/mp4" />浏览器不支持视频播放。</video>{chapters && <p className="cs-caption">时间索引：3.5s 配音与配乐避让 · 8s Logo · 10s CTA</p>}<small>{label} · 原始成片，未重新编码</small></div>;
}
const metrics = [
  ['10/10','Controlled Regression','符合预期的 Case 判断'],['8/8','Automated Repairs','支持自动修复的 Case'],['0','Repair Regressions','修复后新增回归'],['10/10','Planner MATCH','冻结的最终 Planner 轮次'],['14/14','Required Actions','必要动作召回'],['20/20','Planner Parameters','冻结受控用例中的参数匹配'],['6/10','E2E Behavior MATCH','含预期复核与安全停止'],['5/8','Executable E2E','可执行任务完成'],['2/2 → 2/2','A10 Recovery','检测 → 修复，受控注入']
];
export default function CaseStudy() {
 return <main className="case-study">
  <nav className="cs-nav"><Link href="/">← 返回作品集 / DU MING</Link><a href="/resume/">简历</a><a href="/creative-qc-agent/build-log">Technical Appendix ↗</a></nav>
  <header className="cs-hero"><div><p className="cs-kicker">AGENT WORKFLOW · EVALUATION · TARGETED REPAIR</p><h1>Creative QC<br />&amp; Repair Agent</h1><p className="cs-subtitle">面向多模态创作工作流的需求编译、工具规划、自动质检与定向修复 Agent 原型</p><p>输出完成以后，系统如何判断它满足了需求？如果 Logo 出现太晚、配乐没有避让人声，又如何只修正对应部分？</p><p>这个项目把自然语言需求连接到可编辑时间线、真实证据和受约束的修复工具，形成可追踪的执行闭环。</p><div className="cs-actions"><a href="#trace">看一次真实执行 ↓</a><a href="#recovery">查看受控修复</a><a href="/creative-qc-agent/build-log/">技术附录</a></div><p className="cs-caption">3–5 分钟阅读 · 核心系统冻结于 M08 · 本页只整理已存在的证据</p></div><div className="cs-hero-note"><span>THE CORE QUESTION</span><h2>它能证明<br />自己做对了吗？</h2><p>Requirement → Execute → Evidence<br />→ Evaluate → Localize → Repair</p><div className="cs-note-stat"><strong>0 dB → −8 dB</strong><span>A10：真实音频证据中的修复变化</span></div></div></header>
  <section id="system" className="cs-section"><p className="cs-kicker">01 / SYSTEM</p><h2>执行之后，逐项验证需求。</h2><p>任务完成需要两类证据：工具确实执行了编辑，成片也满足当前需求。未通过的条件被定位到具体参数，再交给受限工具修复。</p><ol className="cs-architecture">{['自然语言需求','Requirement Compiler','RequirementSpec','Tool Planner','Editable Timeline','Executor','Evidence Router','Atomic Evaluation','Failure Localization','Targeted Repair','Re-render','Re-evaluate'].map(step=><li key={step}>{step}</li>)}</ol></section>
  <section id="trace" className="cs-section"><p className="cs-kicker">02 / A REAL EXECUTION</p><h2>A03：一次真实的端到端执行。</h2><div className="cs-trace"><Film name="a03" label="A03 · COMPLETED · 8 个自动 Unit PASS" chapters /><div><h3>A03 / 从明确需求到 12 秒成片</h3><details><summary>查看原始需求与阶段状态</summary><pre>{trace.input}</pre><ol className="cs-steps">{trace.stages.map(s=><li key={s.stage}><b>{s.stage}</b><span>{s.status}</span></li>)}</ol></details><p>要求：9:16 输出，安排 VO、Logo、结尾 CTA，并在 VO 期间降低配乐。Compiler 生成结构化需求，Planner 提交工具动作，通过校验后交给 Executor。</p><ol className="cs-steps"><li><b>理解与拆解</b><span>8 个自动条件进入 RequirementSpec；本例未请求 P1 / S1 视觉条件。</span></li><li><b>受约束执行</b><span>补入 Logo、CTA、VO，设置 ducking、时长与尺寸，共 6 个编辑动作。</span></li><li><b>真实证据验证</b><span>时间线、音频电平、成片元数据分别回答对应问题，8 个自动条件全部通过。</span></li></ol><p className="cs-callout">VO 从 3.5s 开始，保留完整音频至约 6.565s；没有为了名义 6s 终点截断原配音。</p><a href={`${base}/evidence/a03.json`}>查看 A03 需求、计划与评测证据 ↗</a></div></div></section>
  <section id="agent-loop" className="cs-section"><p className="cs-kicker">03 / EVALUATION IN THE LOOP</p><h2>评测结果决定下一步动作。</h2><p>每条当前需求都有状态、证据与判断依据。失败项提供 repair_target；修复后重新渲染，用同一 Evaluator 复测全部当前需求，检查原本通过的条件是否回归。</p><p className="cs-callout">自动条件通过不等于整项任务完成。需要视觉复核时保留 REVIEW_REQUIRED；依赖缺失时返回 BLOCKED，不把它算作独立失败。</p></section>
  <section className="cs-section"><p className="cs-kicker">04 / EVIDENCE ROUTER</p><h2>每个问题，使用适合它的证据。</h2><blockquote>“I do not ask an LLM to judge what deterministic evidence can answer.”</blockquote><div className="cs-grid four">{[['Timeline','P3 · P4 · L1 · L2','存在性与时间安排'],['Audio Signal','P2 · L3','VO 证据与 BGM 前后电平'],['Metadata','Q1 · Q2','ffprobe 检查时长与尺寸'],['Vision Frames','P1 · S1','真实抽帧，人工辅助复核']].map(([a,b,c])=><article key={a}><h3>{a}</h3><b>{b}</b><p>{c}</p></article>)}</div></section>
  <section className="cs-section"><p className="cs-kicker">05 / ATOMIC JUDGMENT</p><h2>PLS：把“哪里错了”变成可执行接口。</h2><div className="cs-grid four">{[['POINT','对象是否成立','Logo、CTA、VO 是否存在；关键产品是否可见。'],['LINE','时间与关系是否成立','Logo 出现时间、CTA 区间、VO 与 BGM 的避让关系。'],['SCENE','组合是否成立','产品、护发素与木梳的整体构图是否保留。'],['QUALITY','交付规格是否成立','时长、分辨率与画幅是否符合约定。']].map(([t,h,p])=><article key={t}><span className="cs-kicker">{t}</span><h3>{h}</h3><p>{p}</p></article>)}</div><div className="cs-grid two"><article><h3>P3 FAIL → L1 BLOCKED</h3><p>C02 删除 Logo 后，存在性失败。不存在的 Logo 无法判断出现时机，因此 L1 被依赖阻塞，不计为独立失败。修复父条件后再评估时间。</p></article><article><h3>P1 PASS / S1 FAIL</h3><p>M04 Fault B 中，主体仍可识别，但护发素 / 木梳被严重裁切。单个关键对象成立，不代表整体构图成立。</p><small>来自已有抽帧与人工辅助视觉判断；不属于 A03 的自动评测。</small></article></div></section>
  <section id="recovery" className="cs-section"><p className="cs-kicker">06 / CONTROLLED RECOVERY TEST</p><h2>A10：检测两个错误，只修对应位置。</h2><p>这是在已完成输出上主动注入的受控故障，不是自然发生的 Agent 错误。Logo 从 8s 推迟到 9.2s，BGM ducking 从 −8 dB 改成 0 dB。</p><div className="cs-grid two cs-recovery"><div><Film name="a10-fault" label="注入故障 · L1 FAIL / L3 FAIL" /><h3>9.2s / 0.00 dB</h3><p>Logo 太晚；VO 期间配乐未降低。</p></div><div><Film name="a10-repair" label="定向修复 · L1 PASS / L3 PASS" /><h3>8.0s / −7.99988 dB</h3><p>两项恢复，通过同一 Evaluator 复测，无新增回归。</p></div></div><p className="cs-flow">FAIL → diagnosis → repair_target → constrained tool → Timeline patch → re-render → re-evaluate</p><p>L3 比较同一 VO 区间内处理前、处理后的 BGM 电平，不读取 Timeline 中声明的 −8 dB 来冒充测量结果。</p><a href={`${base}/evidence/a10.json`}>查看故障定义、修复计划与前后评测 ↗</a></section>
  <section id="results" className="cs-section"><p className="cs-kicker">07 / FROZEN RESULTS</p><h2>有效的闭环，也有明确的失败。</h2><div className="cs-grid four cs-metrics">{metrics.map(([v,t,d])=><article key={t}><strong>{v}</strong><h3>{t}</h3><p>{d}</p></article>)}</div><p className="cs-callout">6/10 是端到端预期行为匹配，不是“Agent 准确率 60%”。38/38 仅表示实际被评估的自动条件通过，不代表全部任务成功。不同测试集的分母不可合并。</p><a href={`${base}/evidence/metrics.json`}>查看冻结指标与来源 ↗</a></section>
  <section className="cs-section"><p className="cs-kicker">08 / FAILURES & ITERATION</p><h2>保留失败，比继续调成全绿更有价值。</h2><div className="cs-grid two">{[['M06 · Schema contract','早期 composition target 映射不符合契约，随后澄清通用映射规则。冻结结果仍保留 E07 Schema 错误与 E11 Provider 超时。'],['M07 · Presence is not availability','初轮缺失的 overlay 被判断为已满足。补充通用规则：素材库存中可用，不等于 Timeline 中已存在；最终轮 10/10 MATCH。'],['M08 · A06 / Plan Gate','Compiler 正确省略未要求的 ducking，Planner 却新增该动作。Gate 拒绝整份计划，避免无需求依据的修改。'],['M08 · A07 / Status contract','deferred 请求仍被保留，但 Planner 返回 READY 而非 READY_WITH_DEFERRED。状态契约不合法，计划被阻止。']].map(([h,p])=><article key={h}><h3>{h}</h3><p>{p}</p></article>)}</div><p>A04 / A09 的 Compiler Schema 错误同样保留。M08 单轮运行，无重试；本次作品集整理没有重新调用模型或修改核心系统。</p><a href={`${base}/evidence/e2e-outcomes.json`}>查看全部 10 个 E2E Case 的结局 ↗</a></section>
  <section id="safe-stop" className="cs-section"><p className="cs-kicker">09 / NO-OP & SAFE STOP</p><h2>无需修改和需要澄清，都有明确出口。</h2><div className="cs-grid two"><article><h3>M07 · P09 / ALREADY_SATISFIED</h3><p>0 Tool Calls，未重新渲染。已有证据满足 8 个自动条件，不重复设置相同参数。</p></article><article><h3>M08 · A08 / NEEDS_CLARIFICATION</h3><p>Logo 时机含糊，系统按预期停止。Planner NOT_RUN，Render NOT_RUN，等待需求澄清。</p></article></div></section>
  <section className="cs-section"><p className="cs-kicker">10 / SCOPE & ROLE FIT</p><h2>工程 PoC 的能力与边界。</h2><p>单一源视频、固定且狭窄的素材库存、单一 LLM Provider；未验证跨视频泛化。仅有 10 个受控端到端输入；视觉判断为 REVIEW_ASSISTED（人工辅助复核），没有完全自动化视觉规划；工具来自受控集合，没有开放世界工具发现，也不声称生产级可靠性。</p><div className="cs-grid two"><article><h3>岗位能力 → 项目证据</h3><p>意图理解 → Requirement Compiler<br />任务拆解 → Atomic RequirementSpec<br />Tool Use / Workflow → Planner + constrained tools<br />音视频编辑 → 可编辑 Timeline + FFmpeg Executor</p></article><article><h3>从执行到质量闭环</h3><p>自动质检 → Evidence Router + Atomic Evaluator<br />定向修复 → Diagnostic → Repair Target → Tool Action<br />评测集验证 → Controlled Regression Set<br />评测驱动迭代 → M06 / M07 / M08 真实失败记录</p></article></div><small>按已提供的岗位能力清单映射；未提供完整 JD。项目编辑已有媒体，不声称生成式视频能力。</small></section>
  <footer className="cs-footer"><h2>继续追溯实现。</h2><p>完整阶段记录、里程碑报告和构建过程保留在技术附录。</p><div className="cs-actions"><Link href="/">返回作品集</Link><a href="/creative-qc-agent/build-log">进入 Technical Appendix ↗</a><a href={`${base}/CASE_STUDY.md`}>下载 Case Study</a></div></footer>
 </main>;
}
