import Link from 'next/link';
import trace from './trace.json';
import type { Metadata } from 'next';
import './case-study.css';

export const metadata: Metadata = { title: '创作 Agent 质检与定向修复｜杜明', description: '受控评测的多模态创作 Agent 原型：需求编译、工具规划、自动质检、失败定位与定向修复。', alternates: { canonical: '/creative-qc-agent/' }, openGraph: { title: '创作 Agent 质检与定向修复｜杜明', description: '需求编译、工具规划、自动质检与定向修复 Agent 原型', url: 'https://ventusdu0809.github.io/creative-qc-agent/' } };
const base = '/assets/creative-qc-agent';
function Film({ name, label, chapters = false }: { name: string; label: string; chapters?: boolean }) {
 return <div className="cs-film"><video controls playsInline preload="metadata" poster={`${base}/media/${name}-poster.jpg`} aria-label={label}><source src={`${base}/media/${name === "a10-repair" ? "a03" : name}.mp4`} type="video/mp4" />浏览器不支持视频播放。</video>{chapters && <p className="cs-caption">时间索引：3.5s 配音与配乐避让 · 8s Logo · 10s CTA</p>}<small>{label} · 原始成片，未重新编码</small></div>;
}
const metrics = [
  ['10/10','受控回归','符合预期的案例判断'],['8/8','自动修复','支持自动修复的案例'],['0','新增回归','修复后新增回归'],['10/10','规划匹配 · Planner','冻结的最终 Planner 轮次'],['14/14','必要动作','必要动作召回'],['20/20','规划参数','冻结受控用例中的参数匹配'],['6/10','端到端行为匹配','含预期复核与安全停止'],['5/8','可执行任务完成','可执行任务完成'],['2/2 → 2/2','受控检测 → 修复','检测 → 修复，受控注入']
];
export default function CaseStudy() {
 return <main className="case-study">
  <nav className="cs-nav"><Link href="/">← 返回作品集 / DU MING</Link><a href="/resume/">简历</a><a href="/creative-qc-agent/build-log">技术附录 ↗</a></nav>
  <header className="cs-hero"><div><p className="cs-kicker">创作工作流 · 质检与修复</p><h1>创作 Agent<br />质检与定向修复</h1><p className="cs-subtitle">Creative QC & Repair Agent</p><p>将需求转成编辑动作，检查成片，并修复 Logo 时机、配乐避让等具体问题。</p><p>受控原型：编辑已有媒体，保留每次执行、检查与修复记录。</p><div className="cs-actions"><a href="#trace">看一次真实执行 ↓</a><a href="#recovery">查看受控修复</a><a href="/creative-qc-agent/build-log/">技术附录</a></div><p className="cs-caption">M08 冻结版本 · 真实运行记录</p></div><figure className="cs-hero-still"><img src="/assets/creative-qc-agent/media/a03-poster.jpg" alt="A03 实际输出：竖屏护发产品视频" width="360" height="640"/><figcaption>A03 实际成片 · 12 秒 · 9:16</figcaption><a href="#trace">播放完整案例 ↓</a></figure></header>

  <section id="trace" className="cs-section"><p className="cs-kicker">01 / 真实执行</p><h2>A03：一次真实的端到端执行。</h2><div className="cs-trace"><Film name="a03" label="A03 · 执行完成 COMPLETED · 8 个自动条件通过" chapters /><div><h3>A03 / 从明确需求到 12 秒成片</h3><details><summary>查看原始需求与阶段状态</summary><pre>{trace.input}</pre><ol className="cs-steps">{trace.stages.map(s=><li key={s.stage}><b>{s.stage}</b><span>{s.status}</span></li>)}</ol></details><p>要求：9:16 输出，安排 VO、Logo、结尾 CTA，并在 VO 期间降低配乐。Compiler 生成结构化需求，Planner 提交工具动作，通过校验后交给 Executor。</p><ol className="cs-steps"><li><b>需求编译</b><span>需求规格（RequirementSpec）包含 8 个自动检查条件，本例未要求 P1 / S1 视觉检查。</span></li><li><b>编辑执行</b><span>加入 Logo、结尾文字和配音，设置配乐避让、时长与尺寸，共 6 个编辑动作。</span></li><li><b>成片检查</b><span>时间线、音频电平、成片元数据分别回答对应问题，8 个自动条件全部通过。</span></li></ol><p className="cs-callout">配音从 3.5s 开始，完整播放至约 6.565s，未按名义 6s 终点截断。</p><a href={`${base}/evidence/a03.json`}>查看 A03 需求、计划与评测证据 ↗</a></div></div></section>



  <section id="recovery" className="cs-section"><p className="cs-kicker">02 / 受控修复</p><h2>A10：检测两个错误，只修对应位置。</h2><p>这是在已完成输出上主动注入的受控故障，不是自然发生的 Agent 错误。Logo 从 8s 推迟到 9.2s，BGM ducking 从 −8 dB 改成 0 dB。</p><div className="cs-grid two cs-recovery"><div><Film name="a10-fault" label="注入故障 · L1 FAIL / L3 FAIL" /><h3>9.2s / 0.00 dB</h3><p>Logo 太晚；VO 期间配乐未降低。</p></div><div><Film name="a10-repair" label="定向修复 · L1 PASS / L3 PASS" /><h3>8.0s / −7.99988 dB</h3><p>两项恢复，通过同一 Evaluator 复测，无新增回归。</p></div></div><div className="repair-proof" role="img" aria-label="A10受控修复：Logo从9.2秒回到8秒，配乐避让从0分贝回到约负8分贝"><div><span>Logo 出现时间</span><p>故障 <b>9.2s</b> → 修复 <b>8.0s</b></p><div className="repair-track"><i style={{left:'76.67%'}}/><b style={{left:'66.67%'}}/></div><small>0s — 成片时间线 — 12s</small></div><div><span>配乐电平变化 · 实测</span><p>故障 <b>0.00 dB</b> → 修复 <b>−7.99988 dB</b></p><small>比较同一配音区间的处理前后信号</small></div></div><p className="cs-flow">发现失败 → 定位参数 → 定向修改 → 重新渲染 → 同一标准复测</p><p>L3 的结果来自同一配音区间内处理前后的 BGM 电平测量；时间线中的增益参数单独保留。</p><a href={`${base}/evidence/a10.json`}>查看故障定义、修复计划与前后评测 ↗</a></section>
  <section id="results" className="cs-section"><p className="cs-kicker">03 / 实测结果</p><h2>各项测试的结果</h2><div className="cs-grid four cs-metrics">{metrics.map(([v,t,d])=><article key={t}><strong>{v}</strong><h3>{t}</h3><p>{d}</p></article>)}</div><p className="cs-callout">6/10 是端到端预期行为匹配，不是“Agent 准确率 60%”。38/38 仅表示实际被评估的自动条件通过，不代表全部任务成功。不同测试集的分母不可合并。</p><a href={`${base}/evidence/metrics.json`}>查看冻结指标与来源 ↗</a></section>
  <section className="cs-section"><p className="cs-kicker">04 / 失败与迭代</p><h2>失败原因与停止记录</h2><div className="cs-grid two">{[['M06 · 需求结构错误','初轮构图对象映射错误，随后补充了映射规则。最终记录仍有 E07 需求结构错误和 E11 模型服务超时。'],['M07 · 素材可用与时间线存在性','初轮把尚未加入时间线的叠加元素判为已满足。补充素材库存与时间线的存在性检查后，最终轮 10/10 匹配预期。'],['A06 · 未要求的编辑动作','需求编译未包含配乐避让，Planner 却增加了该动作。计划校验拒绝执行，保留了未要求编辑的失败记录。'],['A07 · 状态与请求不一致','计划保留了待处理请求，但状态返回 READY，未按约定返回 READY_WITH_DEFERRED。校验失败，计划停止执行。']].map(([h,p])=><article key={h}><h3>{h}</h3><p>{p}</p></article>)}</div><p>A04 / A09 因需求结构错误而停止。M08 为单轮运行，无重试；本页沿用冻结结果。</p><a href={`${base}/evidence/e2e-outcomes.json`}>查看 10 个端到端案例的结果 ↗</a></section>
  <section id="safe-stop" className="cs-section"><p className="cs-kicker">05 / 无需修改与安全停止</p><h2>无需修改和需要澄清，都有明确证据</h2><div className="cs-grid two"><article><h3>P09 · 已满足要求 ALREADY_SATISFIED</h3><p>0 Tool Calls，未重新渲染。已有证据满足 8 个自动条件，不重复设置相同参数。</p></article><article><h3>A08 · 需要澄清 NEEDS_CLARIFICATION</h3><p>Logo 时机含糊，系统按预期停止。Planner NOT_RUN，Render NOT_RUN，等待需求澄清。</p></article></div></section>
  <section className="cs-section"><p className="cs-kicker">06 / 项目边界</p><h2>已验证范围与局限。</h2><p>单一源视频、固定且狭窄的素材库存、单一 LLM Provider；未验证跨视频泛化。仅有 10 个受控端到端输入；视觉判断为 REVIEW_ASSISTED（人工辅助复核），没有完全自动化视觉规划；工具来自受控集合，没有开放世界工具发现，也不声称生产级可靠性。</p><div className="cs-grid two"><article><h3>岗位能力 → 项目证据</h3><p>意图理解 → Requirement Compiler<br />任务拆解 → Atomic RequirementSpec<br />Tool Use / Workflow → Planner + constrained tools<br />音视频编辑 → 可编辑 Timeline + FFmpeg Executor</p></article><article><h3>质检与修复</h3><p>自动质检 → Evidence Router + Atomic Evaluator<br />定向修复 → Diagnostic → Repair Target → Tool Action<br />评测集验证 → 受控回归测试集<br />评测驱动迭代 → M06 / M07 / M08 真实失败记录</p></article></div><small>项目编辑已有媒体，不声称具备通用自主视频编辑能力。</small></section>
  <details className="reading-detail" id="system"><summary>工作流程 <span>展开方法与细节</span></summary>  <section className="cs-section"><p className="cs-kicker">方法 / 工作流程</p><h2>执行之后，逐项验证需求。</h2><p>任务完成需要两类证据：工具确实执行了编辑，成片也满足当前需求。未通过的条件被定位到具体参数，再交给受限工具修复。</p><ol className="cs-architecture">{['自然语言需求','Requirement Compiler','RequirementSpec','Tool Planner','Editable Timeline','Executor','Evidence Router','Atomic Evaluation','Failure Localization','Targeted Repair','Re-render','Re-evaluate'].map(step=><li key={step}>{step}</li>)}</ol></section></details>
  <details className="reading-detail" id="agent-loop"><summary>评测如何参与执行 <span>展开方法与细节</span></summary>  <section className="cs-section"><p className="cs-kicker">方法 / 评测如何参与执行</p><h2>评测结果决定下一步动作。</h2><p>每条当前需求都有状态、证据与判断依据。失败项提供 repair_target；修复后重新渲染，用同一 Evaluator 复测全部当前需求，检查原本通过的条件是否回归。</p><p className="cs-callout">自动条件通过不等于整项任务完成。需要视觉复核时保留 REVIEW_REQUIRED；依赖缺失时返回 BLOCKED，不把它算作独立失败。</p></section></details>
  <details className="reading-detail"><summary>证据路由 <span>展开方法与细节</span></summary>  <section className="cs-section"><p className="cs-kicker">方法 / 证据路由</p><h2>每个问题都有相关的证据</h2><blockquote>能直接测量的问题，优先使用确定性证据。</blockquote><div className="cs-grid four">{[['时间线 Timeline','P3 · P4 · L1 · L2','存在性与时间安排'],['音频信号','P2 · L3','VO 证据与 BGM 前后电平'],['成片元数据','Q1 · Q2','ffprobe 检查时长与尺寸'],['画面抽帧','P1 · S1','真实抽帧，人工辅助复核']].map(([a,b,c])=><article key={a}><h3>{a}</h3><b>{b}</b><p>{c}</p></article>)}</div></section></details>
  <details className="reading-detail"><summary>逐项判断与依赖 <span>展开方法与细节</span></summary>  <section className="cs-section"><p className="cs-kicker">方法 / 逐项判断与依赖</p><h2>PLS 评价项与依赖关系</h2><div className="cs-grid four">{[['POINT','所需对象是否存在','Logo、CTA、VO 是否存在；关键产品是否可见。'],['LINE','时间与关系是否符合要求','Logo 出现时间、CTA 区间、VO 与 BGM 的避让关系。'],['SCENE','整体构图是否符合要求','产品、护发素与木梳的整体构图是否保留。'],['QUALITY','交付规格是否符合要求','时长、分辨率与画幅是否符合约定。']].map(([t,h,p])=><article key={t}><span className="cs-kicker">{t}</span><h3>{h}</h3><p>{p}</p></article>)}</div><div className="cs-grid two"><article><h3>P3 FAIL → L1 BLOCKED</h3><p>C02 删除 Logo 后，存在性失败。不存在的 Logo 无法判断出现时机，因此 L1 被依赖阻塞，不计为独立失败。修复父条件后再评估时间。</p></article><article><h3>P1 PASS / S1 FAIL</h3><p>M04 Fault B 中，主体仍可识别，但护发素 / 木梳被严重裁切。单个关键对象成立，不代表整体构图成立。</p><small>来自已有抽帧与人工辅助视觉判断；不属于 A03 的自动评测。</small></article></div></section></details>
  <footer className="cs-footer"><h2>技术附录与证据文件</h2><p>完整阶段记录、里程碑报告和构建过程保留在技术附录。</p><div className="cs-actions"><Link href="/">返回作品集</Link><a href="/creative-qc-agent/build-log">阅读技术附录 ↗</a><a href={`${base}/CASE_STUDY.md`}>下载案例说明</a></div></footer>
 </main>;
}
