import Link from "next/link";
import { siteCopy } from "../src/data/siteCopy";
import "./recruiting.css";

const projects = [
 {id:"av",title:"声画计数与文本要求的偏差",type:"音视频生成评测",image:"/images/portfolio/av-count.jpg",alt:"生成视频中的木筷敲杯计数案例",body:"用两轮、16 个生成样本，区分文本数量偏差与声画计数问题。",note:"文本 3 次 → 画面 4 次 → 声音 4 次；小样本诊断。",href:"/audio-visual-evaluation/",cta:"播放案例与查看结论"},
 {id:"t2a",title:"音效生成的听评与错误分析",type:"文本生成音频 · T2A",image:"/images/portfolio/B0008.png",alt:"B0008 正向参照音频的实际振幅波形",body:"两阶段累计 " + siteCopy.heroCopy.metrics[0].value + " 条正式样本；用盲听、隐藏重复和失败案例检查生成结果。",note:"单一评测人；正式模型比较仅在第二阶段完成。",href:"/t2a-case-study/",cta:"试听样本与查看评测"},
];
export default function Home(){return <main id="top" className="career-home">
 <header className="career-nav"><Link href="/" className="career-brand">杜明 <span>DU MING</span></Link><nav aria-label="主导航"><a href="#projects">精选项目</a><a href="#contact">联系</a><Link href="/point-line-scene-framework/">评测方法</Link><Link href="/resume/">简历</Link></nav><a className="career-contact" href="mailto:mingdu0809@gmail.com">联系我 ↗</a></header>
 <section className="career-hero career-shell"><div><p className="career-eyebrow">AI 音频 · 多模态评测 · 创作 Agent</p><h1>杜明<span>AI 音频与<br/>多模态评测</span></h1><p className="career-intro">声音设计硕士，关注生成音频的听感、声画关系，以及创作 Agent 的质检与修复。</p><div className="career-actions"><a className="career-button" href="#projects">浏览精选项目 ↓</a><Link href="/resume/">查看简历 ↗</Link></div><p className="career-tools">主观听评 · 声画一致性 · PLS · Agent 评测</p></div><figure className="career-hero-image"><img src="/images/portfolio/av-count.jpg" alt="音视频生成评测：木筷敲杯的实际生成画面" width="1200" height="675" fetchPriority="high"/><figcaption>音视频生成评测 · 计数案例</figcaption><Link href="/audio-visual-evaluation/">查看评测 ↗</Link></figure></section>
 <section id="projects" className="career-shell career-section"><div className="career-section-heading"><div><p className="career-eyebrow">精选项目</p><h2>项目案例</h2></div><p>创作 Agent · 音视频评测 · 音频听评</p></div>
 <article className="career-feature"><Link href="/creative-qc-agent/" className="career-agent-image" aria-label="查看创作 Agent 质检与修复案例"><img src="/assets/creative-qc-agent/media/a03-poster.jpg" alt="A03 实际成片：护发产品竖屏视频" width="360" height="640" loading="lazy"/><div className="career-image-caption"><span>实际成片 · A03</span><strong>需求 → 编辑 → 质检 → 修复</strong><small>12 秒 · 9:16 · 查看执行记录 ↗</small></div></Link><div className="career-feature-copy"><p className="career-eyebrow">01 / 创作工作流</p><h3>创作 Agent<br/>质检与定向修复</h3><p className="career-english">Creative QC &amp; Repair Agent</p><p>根据自然语言需求安排编辑动作，检查成片中的时间、音频和画面问题，再修复对应参数。</p><dl className="career-results">{[['受控回归','10/10'],['支持的自动修复','8/8'],['Planner 受控案例','10/10'],['端到端行为匹配','6/10']].map(([a,b])=><div key={a}><dt>{a}</dt><dd>{b}</dd></div>)}</dl><p className="career-note">各项来自不同测试集。6/10 为预期行为匹配，真实失败与安全停止均保留。</p><Link className="career-button" href="/creative-qc-agent/">查看项目案例 ↗</Link><Link className="career-secondary" href="/creative-qc-agent/build-log/">技术附录</Link></div></article>
 <div className="career-grid">{projects.map(p=><article className="career-card" key={p.id}><Link className={`career-cover ${p.id==='t2a'?'career-wave-cover':''}`} href={p.href}><img src={p.image} alt={p.alt} width={p.id==='t2a'?1000:1200} height={p.id==='t2a'?220:675} loading="lazy"/>{p.id==='t2a'&&<span>真实试听样本 B0008 · 音质 OVL 5 / 文本符合度 REL 5</span>}</Link><div className="career-card-body"><p className="career-eyebrow">{p.type}</p><h3>{p.title}</h3><p>{p.body}</p><p className="career-note">{p.note}</p><Link href={p.href}>{p.cta} ↗</Link></div></article>)}</div></section>

 <section id="evaluation-system" className="career-shell career-method"><div><p className="career-eyebrow">评测方法 / PLS</p><h2>点—线—面评测方法</h2><p>分别观察局部事件、事件关系和整体场景，独立记录输出质量。</p><Link href="/point-line-scene-framework/">查看点—线—面方法 ↗</Link></div><div className="career-method-diagram"><div><b>点 · Point</b><span>局部事件</span></div><div><b>线 · Line</b><span>时间与关系</span></div><div><b>面 · Scene</b><span>整体场景</span></div><p>质量 Quality · 独立记录</p></div></section>
 <section id="sound-practice" className="career-shell career-section"><div className="career-section-heading"><div><p className="career-eyebrow">补充项目</p><h2>音频验收与制作实践</h2></div><p>游戏音频 · 运行时排查 · 资产验收</p></div><div className="career-support-grid"><article className="career-card"><Link className="career-cover career-chart-cover" href="/audio-validation-summary/" aria-label="查看7872条音频资产验收"><div><span>音频资产验收 · 项目实测</span><strong>7,872 <small>条</small></strong><div className="career-qc-bar"><i/><b/></div><p>1,922 通过 · 46 待优化 · 5,904 不通过</p></div></Link><div className="career-card-body"><p className="career-eyebrow">音频资产质量控制 / QC</p><h3>音频交付检查</h3><p>定义验收规则、审核检测逻辑，定位响度、峰值和循环衔接问题。</p><p className="career-note">不通过表示命中规则，需复核或返修。</p><Link href="/audio-validation-summary/">查看验收结果 ↗</Link></div></article><aside className="career-game-secondary"><p className="career-eyebrow">其他制作经历</p><h3>游戏音频与交互声音</h3><p>Wwise / FMOD 集成、动态混音与运行时问题排查。</p><Link href="/sound-practice/">查看声音实践 ↗</Link></aside></div></section>
 <footer id="contact" className="career-shell career-footer"><div><p className="career-eyebrow">联系与简历</p><h2>联系我</h2><a className="career-email" href="mailto:mingdu0809@gmail.com">mingdu0809@gmail.com ↗</a></div><div><Link href="/resume/">查看简历 ↗</Link><a href="https://space.bilibili.com/7927779" target="_blank" rel="noreferrer">Bilibili 作品 ↗</a><small>© 2026 杜明</small></div></footer>
 </main>}
